Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/Desktop/photoframestuff/test.py", line 123, in distance_monitor
    self.update_icon_opacity(1.0)  # Fully opaque
  File "/home/pi/Desktop/photoframestuff/test.py", line 134, in update_icon_opacity
    self.add_note_button.set_opacity(opacity)  # Placeholder function
  File "/home/pi/Desktop/photoframestuff/round_button.py", line 38, in set_opacity
    alpha_image = self.adjust_image_opacity(self.btn_image, opacity)
  File "/home/pi/Desktop/photoframestuff/round_button.py", line 46, in adjust_image_opacity
    pil_image = pil_image.convert("RGBA")  # Ensure it is in RGBA format
AttributeError: 'PhotoImage' object has no attribute 'convert'
